export const FILE_UPLOAD_REQUEST = 'FILE_UPLOAD_REQUEST'
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS'
export const FILE_UPLOAD_FAIL = 'FILE_UPLOAD_FAIL'

export const FILE_LIST_REQUEST = 'FILE_LIST_REQUEST'
export const FILE_LIST_SUCCESS = 'FILE_LIST_SUCCESS'
export const FILE_LIST_FAIL = 'FILE_LIST_FAIL'